### PR TITLE
discord.js v14 update

### PR DESCRIPTION
**Pull request by mezotv**
This should technically work now didnt test it though!

Co-Authored-By: Dominik K. <mezo.dsn@gmail.com>

### CODE REVIEW

**Comment by schblondie** [comment]
Will pull and check

**Comment by schblondie** [comment]
Heyja,
you are missing ButtonStyle and node fails because you have unexpected token

**Token**
```
node .
C:\Users\limet\OneDrive\Documents\GitHub\gamebot2\events\slashCreate.js:16
    if (!interaction.type === InteractionType.ApplicationCommand;) return
                                                                ^

SyntaxError: Unexpected token ';'
    at Object.compileFunction (node:vm:353:18)
    at wrapSafe (node:internal/modules/cjs/loader:1040:15)
    at Module._compile (node:internal/modules/cjs/loader:1076:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\limet\OneDrive\Documents\GitHub\gamebot2\bot.js:46:17)
    at Module._compile (node:internal/modules/cjs/loader:1112:14)

Node.js v18.4.0
```
**JS Standard**
```
npx standard --fix
standard: Use JavaScript Standard Style (https://standardjs.com)
  C:\Users\limet\OneDrive\Documents\GitHub\gamebot2\events\messageDelete.js:27:12: Empty block statement. (no-empty)
  C:\Users\limet\OneDrive\Documents\GitHub\gamebot2\events\slashCreate.js:16:65: Parsing error: Unexpected token ; (null)
  C:\Users\limet\OneDrive\Documents\GitHub\gamebot2\interactions\modals\beichten\anonyme_frage.js:47:25: 'ButtonStyle' is not defined. (no-undef)
  C:\Users\limet\OneDrive\Documents\GitHub\gamebot2\interactions\modals\beichten\anonyme_frage.js:67:21: 'ButtonStyle' is not defined. (no-undef)
  C:\Users\limet\OneDrive\Documents\GitHub\gamebot2\interactions\modals\beichten\anonyme_frage.js:71:21: 'ButtonStyle' is not defined. (no-undef)
  C:\Users\limet\OneDrive\Documents\GitHub\gamebot2\interactions\modals\freischalten\ve2Reason.js:73:23: 'ButtonStyle' is not defined. (no-undef)
  C:\Users\limet\OneDrive\Documents\GitHub\gamebot2\interactions\modals\vorschlag\vorschlag_anonym.js:53:21: 'ButtonStyle' is not defined. (no-undef)
  C:\Users\limet\OneDrive\Documents\GitHub\gamebot2\interactions\modals\vorschlag\vorschlag_anonym.js:57:21: 'ButtonStyle' is not defined. (no-undef)
  C:\Users\limet\OneDrive\Documents\GitHub\gamebot2\interactions\modals\vorschlag\vorschlag_anonym.js:61:21: 'ButtonStyle' is not defined. (no-undef)
  C:\Users\limet\OneDrive\Documents\GitHub\gamebot2\interactions\modals\vorschlag\vorschlag_event.js:54:21: 'ButtonStyle' is not defined. (no-undef)
  C:\Users\limet\OneDrive\Documents\GitHub\gamebot2\interactions\modals\vorschlag\vorschlag_event.js:58:21: 'ButtonStyle' is not defined. (no-undef)
  C:\Users\limet\OneDrive\Documents\GitHub\gamebot2\interactions\modals\vorschlag\vorschlag_event.js:62:21: 'ButtonStyle' is not defined. (no-undef)
  C:\Users\limet\OneDrive\Documents\GitHub\gamebot2\interactions\modals\vorschlag\vorschlag_normal.js:54:21: 'ButtonStyle' is not defined. (no-undef)
  C:\Users\limet\OneDrive\Documents\GitHub\gamebot2\interactions\modals\vorschlag\vorschlag_normal.js:58:21: 'ButtonStyle' is not defined. (no-undef)
  C:\Users\limet\OneDrive\Documents\GitHub\gamebot2\interactions\modals\vorschlag\vorschlag_normal.js:62:21: 'ButtonStyle' is not defined. (no-undef)
  C:\Users\limet\OneDrive\Documents\GitHub\gamebot2\interactions\slash\misc\newstory.js:31:21: 'ButtonStyle' is not defined. (no-undef)
  C:\Users\limet\OneDrive\Documents\GitHub\gamebot2\interactions\slash\tools\beichte.js:25:21: 'ButtonStyle' is not defined. (no-undef)
  C:\Users\limet\OneDrive\Documents\GitHub\gamebot2\interactions\slash\tools\beichte.js:29:21: 'ButtonStyle' is not defined. (no-undef)
  C:\Users\limet\OneDrive\Documents\GitHub\gamebot2\interactions\slash\tools\vorschlag.js:25:21: 'ButtonStyle' is not defined. (no-undef)
  C:\Users\limet\OneDrive\Documents\GitHub\gamebot2\interactions\slash\tools\vorschlag.js:29:21: 'ButtonStyle' is not defined. (no-undef)
  C:\Users\limet\OneDrive\Documents\GitHub\gamebot2\interactions\slash\tools\vorschlag.js:33:21: 'ButtonStyle' is not defined. (no-undef)
```

**Comment by schblondie** [comment]
Hello,
thank you for contributing. Your code is indeed working, but I already did the change to DJS14 locally and will change the file strategy completly, so all of your edits would be overwritten anyways. Nonetheless you're always welcome to contribute in future issues, which I will not assigne me to. If you have any open questions feel free to contact me.
Felix

**Comment by mezotv** [comment]
You couldve told me that lol.

**Pull request closed without merging**
